### ISSUE TITLE
Items price

### ISSUE THREAD

**Issue by d-stephane** [MinetestForFun/minercantile#4]
Hello,
How can i define items price, if it's possible ?

**Comment by BetterToAutomateTheWorld** [comment]
I quickly read the code and in my point of view, it's not made (or ready whatever) to set static price for some items.
But, you can set them manually by adding a function in the lua configuration which will use `minercantile.stock.items[itname].price` and set some exception based on `[itname]`

@Cyberpangolin @Panquesito7 @ObaniGemini @LeMagnesium Can surely give you a better answer :)

**Comment by d-stephane** [comment]
After looking in the code I just tested this:
<pre>    ["default:cobble"]       = {["nb"] = 10000, ["price"] = 1},
    ["default:chest_locked"] = {["nb"] = 10000, ["price"] = 10},
</pre>
It works very well :)

**Comment by Panquesito7** [comment]
> After looking in the code I just tested this:
> ...

We should explain how to do this in `README.md`.
What do you think, @Darcidride? 🙂
